import { randomBytes } from "crypto";
import { mkdtempSync, rmSync } from "fs";
import { tmpdir } from "os";
import path from "path";
// eslint-disable-next-line @typescript-eslint/no-require-imports -- s3rver ships CJS only, no usable ESM/type-safe named export shape for this constructor pattern
const S3rver = require("s3rver");

/**
 * A real (in-process, filesystem-backed) S3-compatible server for
 * genuinely exercising src/lib/storage/object-storage-s3.ts — same
 * "real backend under test, not a mock of our own client code" philosophy
 * this project already uses for Postgres (see plans-db.test.ts and every
 * other *-db.test.ts: skipped without a real DATABASE_URL, never run
 * against a mocked db object). s3rver speaks enough of the real S3 HTTP
 * API (signed PUT/GET/HEAD/DELETE) that presigned URLs generated by the
 * real AWS SDK against it behave the same as against a real bucket — a
 * test that PUTs to a presigned URL here is exercising the identical code
 * path the browser's selfie-upload step uses in production.
 *
 * Always available (a devDependency, no external service/credentials
 * needed) — unlike the DB integration tests, these never skip.
 */
export async function startTestObjectStorage(): Promise<{
  bucket: string;
  stop: () => Promise<void>;
}> {
  const bucket = `test-bucket-${randomBytes(6).toString("hex")}`;
  const directory = mkdtempSync(path.join(tmpdir(), "s3rver-test-"));

  const instance = new S3rver({
    port: 0, // OS-assigned free port — avoids collisions between test files
    address: "127.0.0.1",
    silent: true,
    directory,
    resetOnClose: true,
    configureBuckets: [{ name: bucket, configs: [] }],
  });

  const { port } = await new Promise<{ address: string; port: number }>((resolve, reject) => {
    instance.run((err: Error | null, addr: { address: string; port: number }) => {
      if (err) reject(err);
      else resolve(addr);
    });
  });

  process.env.OBJECT_STORAGE_REGION = "us-east-1";
  process.env.OBJECT_STORAGE_BUCKET = bucket;
  process.env.OBJECT_STORAGE_ACCESS_KEY_ID = "S3RVER";
  process.env.OBJECT_STORAGE_SECRET_ACCESS_KEY = "S3RVER";
  process.env.OBJECT_STORAGE_ENDPOINT = `http://127.0.0.1:${port}`;
  process.env.OBJECT_STORAGE_FORCE_PATH_STYLE = "true";

  return {
    bucket,
    stop: () =>
      new Promise<void>((resolve, reject) => {
        instance.close((err: Error | null) => {
          rmSync(directory, { recursive: true, force: true });
          delete process.env.OBJECT_STORAGE_REGION;
          delete process.env.OBJECT_STORAGE_BUCKET;
          delete process.env.OBJECT_STORAGE_ACCESS_KEY_ID;
          delete process.env.OBJECT_STORAGE_SECRET_ACCESS_KEY;
          delete process.env.OBJECT_STORAGE_ENDPOINT;
          delete process.env.OBJECT_STORAGE_FORCE_PATH_STYLE;
          if (err) reject(err);
          else resolve();
        });
      }),
  };
}
